---
title: "Cluster 5 binomial signatures"
author: "Camilo Posso"
date: "04/04/2022"
output: 
  html_document:
    code_folding: hide
    toc: true
editor_options: 
  chunk_output_type: inline
---

## Goal




```{r include=FALSE}
library(dplyr)
library(ggplot2)
library(glmnet)
library(msigdbr)
library(RColorBrewer)

source("../../../util/synapseUtil.R")
source("../../../util/loading_data.R")
source("../../../util/mutational_analysis_helper.R")
source("../../../util/make_plots_util.R")


load("../../../Misc/load.combined.data 3-09-2022.RData")
# load.combined.data()

```



```{r}
cluster_assignments <- read.table("../Data/sample_to_cluster_assignments.txt", sep = "\t")
summary.syn <- "syn26642974"
summary.table <- read.table("../Data/PNNL_clinical_summary_12_08_2021_updated_OS_4patients_02_28_2022.txt") %>%
  as.data.frame()

rownames(summary.table) <- summary.table$labId
summary.table <- summary.table[rownames(meta), ]
meta$vitalStatus <- summary.table$vitalStatus
meta <- meta %>%
  mutate(vitalStatus = case_when(vitalStatus == "Dead" ~ 2,
                                 TRUE ~ 1))
cluster_samples <- cluster_assignments$Barcode.ID

## filtering for complete features
global_features <- global.data %>%
  group_by(Gene) %>%
  summarize(total = n()) %>%
  filter(total == 210) %>%
  pull(Gene)

phospho_features <- phospho.data %>%
  group_by(SiteID) %>%
  summarize(total = n()) %>%
  filter(total == 210) %>%
  pull(SiteID)

RNA_features <- RNA.data %>%
  group_by(Gene) %>%
  summarize(total = n()) %>%
  filter(total == 159) %>%
  pull(Gene)

## Splitting data into train and test.
## Global
global_mat_train <- global.data %>%
  filter(Barcode.ID %in% cluster_samples) %>%
  dplyr::rename(feature = Gene) %>%
  filter(feature %in% global_features) %>%
  pivot_wider(names_from = Barcode.ID, 
              values_from = LogRatio) %>% 
  as.data.frame()
rownames(global_mat_train) <- global_mat_train$feature
global_mat_train <- global_mat_train[, -1] %>% as.matrix()

global_mat_test <- global.data %>%
  filter(!(Barcode.ID %in% cluster_samples)) %>%
  dplyr::rename(feature = Gene) %>%
  filter(feature %in% global_features) %>%
  pivot_wider(names_from = Barcode.ID, 
              values_from = LogRatio) %>% 
  as.data.frame()
rownames(global_mat_test) <- global_mat_test$feature
global_mat_test <- global_mat_test[, -1] %>% as.matrix()

## Phospho
phospho_mat_train <- phospho.data %>%
  filter(Barcode.ID %in% cluster_samples) %>%
  select(Barcode.ID, SiteID, LogRatio) %>%
  dplyr::rename(feature = SiteID) %>%
  filter(feature %in% phospho_features) %>%
  pivot_wider(names_from = Barcode.ID, 
              values_from = LogRatio) %>% 
  as.data.frame()
rownames(phospho_mat_train) <- phospho_mat_train$feature
phospho_mat_train <- phospho_mat_train[, -1] %>% as.matrix()

phospho_mat_test <- phospho.data %>%
  filter(!(Barcode.ID %in% cluster_samples)) %>%
  select(Barcode.ID, SiteID, LogRatio) %>%
  dplyr::rename(feature = SiteID) %>%
  filter(feature %in% phospho_features) %>%
  pivot_wider(names_from = Barcode.ID, 
              values_from = LogRatio) %>% 
  as.data.frame()
rownames(phospho_mat_test) <- phospho_mat_test$feature
phospho_mat_test <- phospho_mat_test[, -1] %>% as.matrix()

## RNA
RNA_mat_train <- RNA.data %>%
  filter(Barcode.ID %in% cluster_samples) %>%
  dplyr::rename(feature = Gene,
                LogRatio = `RNA counts`) %>%
  filter(feature %in% RNA_features)  %>%
  pivot_wider(names_from = Barcode.ID, 
              values_from = LogRatio) %>% 
  as.data.frame()
rownames(RNA_mat_train) <- RNA_mat_train$feature
RNA_mat_train <- RNA_mat_train[, -1] %>% as.matrix()

## Standardizing
global_mat_train <- sweep(global_mat_train, 1, apply(global_mat_train, 1, mean), FUN = '-')
global_mat_train <- sweep(global_mat_train, 1, apply(global_mat_train, 1, sd), FUN = '/')
global_mat_test <- sweep(global_mat_test, 1, apply(global_mat_test, 1, mean), FUN = '-')
global_mat_test <- sweep(global_mat_test, 1, apply(global_mat_test, 1, sd), FUN = '/')

phospho_mat_train <- sweep(phospho_mat_train, 1, apply(phospho_mat_train, 1, mean), FUN = '-')
phospho_mat_train <- sweep(phospho_mat_train, 1, apply(phospho_mat_train, 1, sd), FUN = '/')
phospho_mat_test <- sweep(phospho_mat_test, 1, apply(phospho_mat_test, 1, mean), FUN = '-')
phospho_mat_test <- sweep(phospho_mat_test, 1, apply(phospho_mat_test, 1, sd), FUN = '/')

RNA_mat_train <- sweep(RNA_mat_train, 1, apply(RNA_mat_train, 1, mean), FUN = '-')
RNA_mat_train <- sweep(RNA_mat_train, 1, apply(RNA_mat_train, 1, sd), FUN = '/')

## Setting up metadata for training models
enet_meta <- left_join(meta, cluster_assignments, by = "Barcode.ID") %>%
  filter(!is.na(k.5)) %>%
  mutate(overallSurvival = as.numeric(overallSurvival),
         k.5 = as.character(k.5)) %>%
  select(Barcode.ID, overallSurvival, vitalStatus, k.5)
rownames(enet_meta) <- enet_meta$Barcode.ID

```


Loading model results.


```{r}
all_results <- readRDS("elastic_net_binomial_models/elastic_net_binomial_results_k_5.RDS")
all_bounds <- readRDS("elastic_net_binomial_models/all_bounds.RDS")
bound_mult <- all_bounds$bound_mult

```



Getting cluster signatures.



```{r}
get_signature <- function(chosen_cluster, chosen_alpha, chosen_type){
  if (chosen_type == "Global"){
    data_mat <- global_mat_train
  } else if (chosen_type == "Phospho"){
    data_mat <- phospho_mat_train
  } else {
    data_mat <- RNA_mat_train
  }
  
  result_name <- paste("Cluster", chosen_cluster, chosen_type)
  cluster_lab <- paste("Cluster", chosen_cluster)
  xx <- all_results[[result_name]]
  
  min_bounds <- all_bounds[[paste0("min_bounds_", chosen_type)]]
  max_bounds <- all_bounds[[paste0("max_bounds_", chosen_type)]]
  min_lambda <- min_bounds[as.character(chosen_alpha), chosen_cluster]
  max_lambda <- max_bounds[as.character(chosen_alpha), chosen_cluster]
  allowed_lambda <- (as.numeric(rownames(xx)) < max_lambda) & 
                    (as.numeric(rownames(xx)) > min_lambda)
  
  xx <- xx[allowed_lambda, ]
  col_name <- paste("alpha =", chosen_alpha)
  chosen_lambda <- rownames(xx)[[which.min(xx[[col_name]])]] %>%
    as.numeric()
  
  cluster_bool <- enet_meta %>%
    dplyr::mutate(cluster_bool = case_when(k.5 == chosen_cluster ~ cluster_lab,
                                      TRUE ~ paste("Not", cluster_lab))) %>%
    pull(cluster_bool) %>%
    as.factor()
  
  names(cluster_bool) <- enet_meta$Barcode.ID
  cluster_bool <- cluster_bool[colnames(data_mat)]
  model <- glmnet(x = t(data_mat),
                  y = cluster_bool,
                  family = 'binomial',
                  alpha = chosen_alpha,
                  lambda = chosen_lambda)
  
  coefs <- coef(model, s = model$lambda) %>% as.matrix()
  sigs <- rownames(coefs)[coefs != 0]
  signatures <- data.frame(Cluster = chosen_cluster, Gene = sigs, 
                           alpha = chosen_alpha, chosen_type = chosen_type,
                           lambda = chosen_lambda) %>%
    filter(Gene != "(Intercept)")
  return(signatures)
}

signatures <- lapply(c("Global", "Phospho", "RNA"), function(chosen_type){
  lapply(c(0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0), function(chosen_alpha){
    test <- lapply(c("1", "2", "3", "4", "5"), get_signature, chosen_alpha, chosen_type) %>%
      do.call("rbind", .)
  }) %>% do.call("rbind", .)
}) %>% do.call("rbind", .)

write.table(signatures, "elastic_net_binomial_models/enet_binomial_all_signatures.txt", 
            sep = "\t", quote = F)

```


```{r eval=FALSE, include=FALSE}
# signatures <- read.table("elastic_net_binomial_models/enet_binomial_all_signatures.txt", sep = "\t")

```

Signature heatmap


```{r}
chosen.colors <- subtype_colors[1:5]
chosen_alpha <- 0.1
data_type <- "RNA"

if (data_type == "Global"){
    data_mat <- global_mat_train
  } else if (data_type == "Phospho"){
    data_mat <- phospho_mat_train
  } else {
    data_mat <- RNA_mat_train
  }

signatures <- signatures %>%
  group_by(chosen_type, alpha, Gene) %>%
  dplyr::mutate(total = n()) %>%
  ungroup()

row_df <- signatures %>%
  dplyr::filter(alpha == chosen_alpha) %>%
  dplyr::filter(chosen_type == data_type) %>%
  dplyr::select(Gene, Cluster) %>%
  group_by(Gene) %>%
  dplyr::mutate(total = n()) %>%
  dplyr::mutate(Cluster = case_when(total == 1 ~ as.character(Cluster),
                                    TRUE ~ "Mixed"),
                Cluster = factor(Cluster, levels = c("1", "2", "3", "4", "5", "Mixed"))) %>%
  unique() %>%
  as.data.frame()
rownames(row_df) <- row_df$Gene

col_df <- meta %>%
  dplyr::select(Barcode.ID) %>%
  merge(cluster_assignments, by = "Barcode.ID") %>%
  dplyr::select(k.5, Barcode.ID) %>%
  dplyr::rename(Cluster = k.5) %>%
  dplyr::mutate(Cluster = as.factor(Cluster)) 
rownames(col_df) <- col_df$Barcode.ID
col_df <- col_df %>%
  select(Cluster)

ann_colors <- list("Cluster" = c("1" = chosen.colors[[1]], 
                                 "2" = chosen.colors[[2]],
                                 "3" = chosen.colors[[3]],
                                 "4" = chosen.colors[[4]],
                                 "5" = chosen.colors[[5]],
                                 "Mixed" = "grey"))

heatmap_breaks <- seq(-3, 3, by = 0.2)
heatmap_colors <- colorRampPalette(rev(brewer.pal(n = 10, name = "RdYlBu")))(length(heatmap_breaks))
cluster_row = pheatmap:::cluster_mat(data_mat[rownames(row_df), ], distance = "euclidean", 
                                     method = "ward.D")
row_df <- row_df[cluster_row$order, ] %>%
  mutate(order = 1:n()) %>%
  arrange(Cluster) %>%
  select(Cluster)
sigs <- rownames(row_df)
file_path <- paste0("./elastic_net_binomial_models/enet_binomial_signature_heatmap_mult_", bound_mult,
                    "_", data_type)

make.pheatmap(data_mat[sigs, ], filename = file_path, format = "pdf",
              scale = "row", cluster_rows = FALSE, clustering_method = "ward.D", 
              annotation_col = col_df, annotation_row = row_df, annotation_colors = ann_colors,
              breaks = heatmap_breaks, color = heatmap_colors, show_rownames = F, show_colnames = F,
              main = paste0(length(sigs), " total features, alpha = ", chosen_alpha), height = 7, width = 7)

```




