name: beatAML_env_37
channels:
  - conda-forge
dependencies:
  - python>=3.7
  - open-fonts
  - numpy>=1.16.4
  - seaborn<=0.9.0
  - python-igraph
  - pycairo
  - scipy>=1.3.0
  - ipython
  - pandas>=1.1.0
  - matplotlib>=2.2.3
  - matplotlib-base>=2.2.3
  - plotly<=2.7.0
  - jupyter
  - networkx=2.3
  - statsmodels
  - Jinja2>=2.10.1
  - requests
  - defusedxml
  - pydot
  - appdirs
  - sortedcontainers
  - pathos
  - openpyxl
  - scikit-learn
  - fastcluster
  - pip
  - itertools
  - pip:
      - matplotlib_venn==0.11.5
      - bioservices
      - synapseclient
      - py2cytoscape==0.7.1
      - wordcloud
      - xgboost
      - tqdm
      - xlrd
      - tables
      - magine