name: beatAML_env_37
channels:
  - conda-forge
dependencies:
  - python>3.7
  - open-fonts
  - numpy
  - seaborn
  - scipy
  - pandas
  - matplotlib
  - statsmodels
  - scikit-learn
  - fastcluster
  - pip
  - pip:
      - synapseclient
      - wordcloud
      - xgboost
      - tqdm
      - xlrd
      - tables
