---
title: "NMF raw results"
author: "Camilo Posso"
date: "`r format(Sys.Date(), '%m/%d/%Y')`"
output: html_document
---

```{r setup}
library(MSnSet.utils)
library(NMF)
library(dplyr)
library(tibble)
library(tidyr)


source("../../util/synapseUtil.R")
source("../../util/loading_data.R")
source("NMF_helper.R")
load.combined.data()

```


```{r}
m.RNA <- make.msnset(RNA.data, feature.col = "Gene", 
                     value.col = "RNA counts", metadata = meta)

m.global <- make.msnset(global.data, feature.col = "Gene", 
                     value.col = "LogRatio", metadata = meta)

m.phospho <- make.msnset(phospho.data, feature.col = "SiteID", 
                     value.col = "LogRatio", metadata = meta)

WES.samples <- unique(WES.data$Barcode.ID)
all.samples <- colnames(exprs(m.global))
samples.complement <- setdiff(all.samples, WES.samples)


## Adding all samples to the WES.data table, since any sample not present indicates
## a mutation status of FALSE.
WES.data.padding <- data.frame(Barcode.ID = samples.complement, 
                               Gene = "FLT3", t_vaf = NA, wesMutation = FALSE)


## A few feature + sample combinations are duplicated with different t_vaf, but of course wesMutation = TRUE.
## So we group those and report the binary mutation.
WES.data.numerical <- WES.data %>%
  rbind(WES.data.padding) %>%
  group_by(Barcode.ID, Gene) %>%
  summarise(wesMutation = all(wesMutation)) %>%
  ungroup(Barcode.ID, Gene) %>%
  mutate(wesMutation = case_when(wesMutation ~ 1,
                                 !wesMutation ~ 0))

m.WES <- make.msnset(WES.data.numerical, feature.col = "Gene", 
                      value.col = "wesMutation", metadata = meta)


mat.global <- exprs(m.global)

mat.phospho <- exprs(m.phospho)

mat.RNA <- exprs(m.RNA)

mat.WES <- exprs(m.WES)
## Impute missing values with zero, meaning no mutation
mat.WES[is.na(mat.WES)] <- 0

datasets <- list(mat.global, mat.phospho, mat.RNA, mat.WES)
samples.common <- Reduce(intersect, lapply(datasets, colnames))
WES.sd <- apply(mat.WES[, samples.common], 1, sd) %>%
  data.frame(Gene = rownames(mat.WES), sd = .)

varying.WES.features <- WES.sd %>%
  filter(sd != 0) %>%
  pull(Gene)

mat.WES <- mat.WES[varying.WES.features, ]

mat <- prepare.nmf.mat(list(mat.global, mat.phospho, mat.RNA, mat.WES))

```


```{r}
start <- Sys.time()
results <- nmf.clustering(mat, n.clusters = c(2, 3, 4, 5, 6, 7, 8), N.trials = 50, prefix = "BEATAML NMF")
# results <- nmf.clustering(mat, n.clusters = c(9,10,11,12,13), N.trials = 20, prefix = "BEATAML")
print(Sys.time() - start)

```




















