---
title: "K = 4 multinomial predictions"
author: "Camilo Posso"
date: "04/27/2022"
output: 
  html_document:
    code_folding: hide
    toc: true
editor_options: 
  chunk_output_type: inline
---

## Goal




```{r include=FALSE}
library(dplyr)
library(ggplot2)
library(kableExtra)
library(glmnet)
library(survminer)
library(survival)
library(gridExtra)
library(grid)
library(ggpattern)

source("../NMF_helper.R")
source("../cluster_model_helper.R")

```


Loading model results.


```{r}
all_results <- readRDS("enet_multinomial_data/elastic_net_multinomial_results_k_4.RDS")
all_bounds <- readRDS("enet_multinomial_data/all_bounds.RDS")
bound_mult <- all_bounds$bound_mult

```



Here we train a prediction model using the full dataset and the best performing hyperparameters
to extend cluster 4 (good prognosis) to the 51 unclustered samples.


```{r}

make_prediction <- function(chosen_alpha, data_type, robust){
  if (data_type == "Global"){
    data_mat <- global_mat_train
    data_mat_test <- global_mat_test
    data_mat_full <- global.data %>%
      dplyr::rename(feature = Gene) %>%
      filter(feature %in% global_features) %>%
      pivot_wider(names_from = Barcode.ID, 
                  values_from = LogRatio) %>% 
      as.data.frame()
    rownames(data_mat_full) <- data_mat_full$feature
    data_mat_full <- data_mat_full[, -1] %>% as.matrix()
  } else if (data_type == "Phospho"){
    data_mat <- phospho_mat_train
    data_mat_test <- phospho_mat_test
    data_mat_full <- phospho.data %>%
      select(Barcode.ID, SiteID, LogRatio) %>%
      dplyr::rename(feature = SiteID) %>%
      filter(feature %in% phospho_features) %>%
      pivot_wider(names_from = Barcode.ID, 
                  values_from = LogRatio) %>% 
      as.data.frame()
    rownames(data_mat_full) <- data_mat_full$feature
    data_mat_full <- data_mat_full[, -1] %>% as.matrix()
  }
  
  xx <- all_results[[data_type]]
  data_mat_full <- sweep(data_mat_full, 1, apply(data_mat_full, 1, mean), FUN = '-')
  data_mat_full <- sweep(data_mat_full, 1, apply(data_mat_full, 1, sd), FUN = '/')
  
  ## Key line
  if (robust){
    data_mat_test <- data_mat_full[, colnames(data_mat_test)]
  }
  
  min_bounds <- all_bounds[[paste0("min_bounds_", data_type)]]
  max_bounds <- all_bounds[[paste0("max_bounds_", data_type)]]
  min_lambda <- min_bounds[as.character(chosen_alpha), ]
  max_lambda <- max_bounds[as.character(chosen_alpha), ]
  allowed_lambda <- (as.numeric(rownames(xx)) < max_lambda) & 
                    (as.numeric(rownames(xx)) > min_lambda)
  
  xx <- xx[allowed_lambda, ]
  col_name <- paste("alpha =", chosen_alpha)
  chosen_lambda <- rownames(xx)[[which.min(xx[[col_name]])]] %>%
    as.numeric()
  print(chosen_lambda)
  
  cluster_lab <- enet_meta %>%
    mutate(cluster_lab = paste("Cluster", k.4)) %>%
    pull(cluster_lab) %>%
    as.factor()
  names(cluster_lab) <- enet_meta$Barcode.ID
  cluster_lab <- cluster_lab[colnames(data_mat)]

  model <- glmnet(x = t(data_mat),
                  y = cluster_lab,
                  family = 'multinomial',
                  alpha = chosen_alpha,
                  lambda = chosen_lambda)
  
  cluster_predictions <- predict(model, s = chosen_lambda, 
                                 newx = t(data_mat_test), 
                                 type = "response")[, , 1] %>% as.data.frame()
  colnames(cluster_predictions) <- paste("New", colnames(cluster_predictions))
  cluster_predictions$max_new <- apply(cluster_predictions, 1, max) %>% unname()
  cluster_predictions$pred_cluster <- predict(model, s = chosen_lambda, 
                                              newx = t(data_mat_test), 
                                              type = "class")
  cluster_predictions$Barcode.ID <- rownames(cluster_predictions)
  
  cluster_predictions_full <- predict(model, s = chosen_lambda, 
                                      newx = t(data_mat_full), 
                                      type = "response")[, , 1] %>% as.data.frame()
  colnames(cluster_predictions_full) <- paste("Full", colnames(cluster_predictions_full))
  cluster_predictions_full$max_full <- apply(cluster_predictions_full, 1, max) %>% unname()
  cluster_predictions_full$pred_cluster_v2 <- predict(model, s = chosen_lambda, 
                                                      newx = t(data_mat_full), 
                                                      type = "class")
  cluster_predictions_full$Barcode.ID <- rownames(cluster_predictions_full)
  
  out <- full_join(cluster_predictions, cluster_predictions_full, by = "Barcode.ID")
  return(out)
}


make_prediction_plot <- function(chosen_alpha, data_type, confidence_cutoff = 0.40, robust = TRUE){
  cluster_predictions <- make_prediction(chosen_alpha, data_type, robust) %>%
    mutate(pred_cluster = sub("Cluster ", "", pred_cluster),
           pred_cluster_v2 = sub("Cluster ", "", pred_cluster_v2))
  if (robust){
    path_ending <- "_robust_normalization.pdf"
  } else {
    path_ending <- ".pdf"
  }
  
  meta_c <- left_join(meta, cluster_assignments, by = "Barcode.ID") %>%
    mutate(overallSurvival = as.numeric(overallSurvival),
           k.4 = as.character(k.4)) %>%
    left_join(cluster_predictions, by = "Barcode.ID")
  rownames(meta_c) <- meta_c$Barcode.ID
  
  meta_c_new <- meta_c %>%
      filter(is.na(k.4)) %>%
    mutate(conf = case_when(max_new <= confidence_cutoff ~ "Low confidence",
                            TRUE ~ "OK")) %>%
    dplyr::rename(Cluster = pred_cluster)
  meta_c_plot <- meta_c_new %>%
    filter(conf == "OK")
  meta_c_train <- meta_c %>%
    filter(!is.na(k.4)) %>%
    dplyr::rename(Cluster = k.4)
  
  plot_title <- paste0("Predicting on 51 new samples, conf > ", 
                       confidence_cutoff, "(", nrow(meta_c_plot), " samples)")
  color_palette <- c("1" = subtype_colors[[1]],
                     "2" = subtype_colors[[2]],
                     "3" = subtype_colors[[3]],
                     "4" = subtype_colors[[4]])
  
  sfit <- survfit(Surv(overallSurvival, vitalStatus) ~ Cluster, data = meta_c_train)
  p1 <- ggsurvplot(sfit, color = "Cluster", data = meta_c_train,
                   palette = color_palette)$plot +
          theme(legend.text = element_text(size = 12, color = "black"),
                legend.title = element_text(size = 12, color = "black")) + 
          ggtitle("159 Clustered samples")
  
  meta_c$Cluster <- meta_c$pred_cluster_v2
  sfit <- survfit(Surv(overallSurvival, vitalStatus) ~ Cluster, data = meta_c)
  p2 <- ggsurvplot(sfit, color = "Cluster", data = meta_c,
                   palette = color_palette)$plot +
          theme(legend.text = element_text(size = 12, color = "black"),
                legend.title = element_text(size = 12, color = "black")) + 
          ggtitle("Predicting on all 210 samples")
  
  sfit <- survfit(Surv(overallSurvival, vitalStatus) ~ Cluster, data = meta_c_plot)
  p3 <- ggsurvplot(sfit, color = "Cluster", data = meta_c_plot,
                   palette = color_palette)$plot +
          theme(legend.text = element_text(size = 12, color = "black"),
                legend.title = element_text(size = 12, color = "black")) +
          ggtitle(plot_title)
  
  sfit <- survfit(Surv(overallSurvival, vitalStatus) ~ Cluster, data = meta_c_new)
  p4 <- ggsurvplot(sfit, color = "Cluster", data = meta_c_new,
                   palette = color_palette)$plot +
          theme(legend.text = element_text(size = 12, color = "black"),
                legend.title = element_text(size = 12, color = "black")) + 
          ggtitle("Predicting on 51 new samples")
  
  p_all <- arrangeGrob(p1, p2, p4, ncol = 2, nrow = 2,
                       top = textGrob(paste0("Survival plots, ", data_type, ", alpha = ", chosen_alpha), 
                                      gp = gpar(fontsize = 20)))
  ggsave(paste0("enet_multinomial_data/predicted_survival_", 
                data_type, "_", chosen_alpha, path_ending), 
         width = 16, height = 12, p_all)
  return(list(p1, p2, p4))
}

```



```{r eval=FALSE, include=FALSE}
lapply(c(0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0), function(chosen_alpha){
  make_prediction_plot(chosen_alpha, "Global", robust = TRUE)
  make_prediction_plot(chosen_alpha, "Phospho", robust = TRUE)
  make_prediction_plot(chosen_alpha, "Global", robust = FALSE)
  make_prediction_plot(chosen_alpha, "Phospho", robust = FALSE)
})

prediction_survival_plots <- make_prediction_plot(0.7, "Global", robust = TRUE)
ggsave("enet_multinomial_data/prediction_survival_alpha_0.7_all_samples.pdf", 
       width = 7, height = 7, plot = prediction_survival_plots[[2]])
ggsave("enet_multinomial_data/prediction_survival_alpha_0.7_heldout_samples.pdf", 
       width = 7, height = 7, plot = prediction_survival_plots[[3]])

```



```{r}
all_mutation_data <- load_mutational_sample_data()
mutation_data <- all_mutation_data %>%
  mutate(value = TRUE) %>%
  pivot_wider(names_from = Gene, values_from = value, values_fn = any)
mutation_data <- mutation_data[, c("Barcode.ID", "KRAS+NRAS", "NPM1_clinical")] %>%
  full_join(meta[, c("Barcode.ID", "FLT3.ITD")], by = "Barcode.ID") %>%
  mutate(RAS = case_when(!is.na(`KRAS+NRAS`) ~ `KRAS+NRAS`,
                          TRUE ~ FALSE),
         NPM1_clinical = case_when(!is.na(NPM1_clinical) ~ NPM1_clinical,
                                   TRUE ~ FALSE),
         FLT3 = case_when(FLT3.ITD == "TRUE" ~ TRUE,
                          TRUE ~ FALSE)) %>%
  select(Barcode.ID, FLT3, NPM1_clinical, RAS)
```



```{r}
mut_enrichment <- function(sample_categories, assignments, log.scale = FALSE) {
  k = length(unique(assignments$Cluster))
  
  sample_categories <- sample_categories %>%
    filter(rownames(.) %in% rownames(assignments)) %>%
    left_join(assignments, by = "Barcode.ID") %>%
    column_to_rownames("Barcode.ID") %>% 
    as.data.frame()
  
  categories <- sample_categories %>%
    select(-Cluster) %>%
    colnames()
  
  out <- lapply(categories, function(category){
    
    p.values <- lapply(1:k, function(i){
      cluster.df <- sample_categories %>%
        mutate(Cluster = case_when(Cluster == i ~ TRUE,
                                   TRUE ~ FALSE)) %>%
        mutate(Cluster = as.factor(Cluster))
      dat <- table(cluster.df[[category]], cluster.df$Cluster)
      background_dist <- apply(dat, 1, sum)
      background_prop <- background_dist[[2]]/(background_dist[[2]] + background_dist[[1]])
      cluster_prop <- dat[2, 2]/(dat[1, 2] + dat[2, 2])
      p_value <- fisher.test(dat, workspace = 2e8, alternative = "greater")$p.value
      if (log.scale) {
        p_value <- -log10(p_value)
      } else {
        p_value <- p_value
      }
      xx <- data.frame(background_prop, cluster_prop, p_value)
      colnames(xx) <- c(paste("Background", category, "positive fraction"),
                        paste(category, "positive fraction"),
                        paste("Enrichment", category, "p-value"))
      rownames(xx) <- paste("Cluster", i)
      return(xx)
    }) %>% do.call("rbind", .)
    
  }) %>% do.call(cbind, .) %>% 
    as.data.frame()
  return(out)
}


mut_enrichment_plot <- function(chosen_alpha, data_type, robust = TRUE){
  if (robust){
    path_ending <- "_robust_normalization.pdf"
  } else {
    path_ending <- ".pdf"
  }
  
  meta_pred <- make_prediction(chosen_alpha, data_type, robust) %>%
    select(Barcode.ID, pred_cluster, pred_cluster_v2) %>%
    full_join(mutation_data, by = "Barcode.ID") %>%
    mutate(pred_cluster = sub("Cluster ", "", pred_cluster),
           pred_cluster_v2 = sub("Cluster ", "", pred_cluster_v2))
  rownames(meta_pred) <- meta_pred$Barcode.ID
  
  sample_assn <- meta_pred[, c("Barcode.ID", "pred_cluster")] %>%
    dplyr::rename(Cluster = pred_cluster) %>%
    filter(!is.na(Cluster))
  sample_cats <- meta_pred[rownames(sample_assn), c("Barcode.ID", "FLT3", "RAS", "NPM1_clinical")]
  mutation_enrichment <- mut_enrichment(sample_cats, sample_assn) %>%
    mutate(Cluster = 1:4) %>%
    mutate(pred_type = "51 Samples")
  
  sample_assn <- meta_pred[, c("Barcode.ID", "pred_cluster_v2")] %>%
    dplyr::rename(Cluster = pred_cluster_v2) %>%
    filter(!is.na(Cluster))
  sample_cats <- meta_pred[rownames(sample_assn), c("Barcode.ID", "FLT3", "RAS", "NPM1_clinical")]
  mutation_enrichment <- mut_enrichment(sample_cats, sample_assn) %>%
    mutate(Cluster = 1:4) %>%
    mutate(pred_type = "210 Samples") %>%
    rbind(mutation_enrichment)
  
  sample_assn <- enet_meta[, c("Barcode.ID", "k.4")] %>%
    dplyr::rename(Cluster = k.4) %>%
    filter(!is.na(Cluster)) 
  sample_cats <- meta_pred[rownames(sample_assn), c("Barcode.ID", "FLT3", "RAS", "NPM1_clinical")]
  mutation_enrichment <- mut_enrichment(sample_cats, sample_assn) %>%
    mutate(Cluster = 1:4) %>%
    mutate(pred_type = "159 Samples") %>%
    rbind(mutation_enrichment) %>%
    mutate(pred_type = factor(pred_type, levels = c("159 Samples", 
                                                    "210 Samples",
                                                    "51 Samples")))
  
  plot_df1 <- mutation_enrichment %>%
    select(Cluster, `FLT3 positive fraction`,
           `Enrichment FLT3 p-value`, pred_type) %>%
    dplyr::rename(`P-value` = `Enrichment FLT3 p-value`,
                  `Fraction mutated` = `FLT3 positive fraction`,
                  `Type` = pred_type) %>%
    mutate(`Significant enrichment` = case_when(`P-value` < 0.05 ~ 1,
                                   TRUE ~ 0))
  p1 <- ggplot(plot_df1, aes(x = Cluster, y = `Fraction mutated`, 
                             group = `Type`, 
                             fill = `Type`)) + 
    geom_bar(stat = "identity", pos = position_dodge(), width = 0.77, alpha = 0.7) + 
    scale_fill_manual(values = prediction_colors) +
    geom_col_pattern(aes(x = Cluster, y = `Fraction mutated`,
                         pattern_alpha = `Significant enrichment`),
                     width = 0.77,  pos = position_dodge(),
                     pattern = 'stripe',
                     color = 'black') +
    scale_pattern_alpha(guide = "none") + 
    ggtitle("FLT3 Status") + ylim(0, 1)
  
  plot_df2 <- mutation_enrichment %>%
    select(Cluster, `RAS positive fraction`,
           `Enrichment RAS p-value`, pred_type) %>%
    dplyr::rename(`P-value` = `Enrichment RAS p-value`,
                  `Fraction mutated` = `RAS positive fraction`,
                  `Type` = pred_type) %>%
    mutate(`Significant enrichment` = case_when(`P-value` < 0.05 ~ 1,
                                   TRUE ~ 0))
  p2 <- ggplot(plot_df2, aes(x = Cluster, y = `Fraction mutated`, 
                             group = `Type`, 
                             fill = `Type`)) + 
    geom_bar(stat = "identity", pos = position_dodge(), width = 0.77, alpha = 0.7) + 
    scale_fill_manual(values = prediction_colors) +
    geom_col_pattern(aes(x = Cluster, y = `Fraction mutated`,
                         pattern_alpha = `Significant enrichment`),
                     width = 0.77,  pos = position_dodge(),
                     pattern = 'stripe',
                     color = 'black') +
    scale_pattern_alpha(guide = "none") + 
    ggtitle("RAS Status") + ylim(0, 1)
  
  plot_df3 <- mutation_enrichment %>%
    select(Cluster, `NPM1_clinical positive fraction`,
           `Enrichment NPM1_clinical p-value`, pred_type) %>%
    dplyr::rename(`P-value` = `Enrichment NPM1_clinical p-value`,
                  `Fraction mutated` = `NPM1_clinical positive fraction`,
                  `Type` = pred_type) %>%
    mutate(`Significant enrichment` = case_when(`P-value` < 0.05 ~ 1,
                                   TRUE ~ 0))
  p3 <- ggplot(plot_df3, aes(x = Cluster, y = `Fraction mutated`, 
                             group = `Type`, 
                             fill = `Type`)) + 
    geom_bar(stat = "identity", pos = position_dodge(), width = 0.77, alpha = 0.7) + 
    scale_fill_manual(values = prediction_colors) +
    geom_col_pattern(aes(x = Cluster, y = `Fraction mutated`,
                         pattern_alpha = `Significant enrichment`),
                     width = 0.77,  pos = position_dodge(),
                     pattern = 'stripe',
                     color = 'black') +
    scale_pattern_alpha(guide = "none") + 
    ggtitle("NPM1_clinical Status") + ylim(0, 1)
  
  p_all <- arrangeGrob(p1, p2, p3, ncol = 3,
                       top = textGrob(paste0("Mutation Status - ", data_type, " predicions - alpha = ", chosen_alpha), 
                                      gp = gpar(fontsize = 20)))
  
  ggsave(paste0("enet_multinomial_data/predicted_mutation_status_", 
                  data_type, "_", chosen_alpha, path_ending), 
           width = 15, height = 5, p_all)
  
  return(mutation_enrichment)
}

```



```{r}
sanity_check <- mut_enrichment_plot(0.7, "Global", TRUE)

```


```{r eval=FALSE, include=FALSE}
predictions <- make_prediction(0.7, "Global", TRUE) %>%
  select(Barcode.ID, pred_cluster_v2) %>%
  dplyr::rename(Cluster = pred_cluster_v2) %>%
  mutate(Cluster = as.character(Cluster))

write.table(predictions, "enet_multinomial_data/full_210_prediction_cluster_assignments_k4.txt", sep = "\t")
upload.plot("enet_multinomial_data/full_210_prediction_cluster_assignments_k4.txt", "syn29612385")

```



