---
title: "Cluster 5 binomial signatures"
author: "Camilo Posso"
date: "04/04/2022"
output: 
  html_document:
    code_folding: hide
    toc: true
editor_options: 
  chunk_output_type: inline
---

## Goal




```{r include=FALSE}
library(dplyr)
library(ggplot2)
library(glmnet)
library(msigdbr)
library(RColorBrewer)
library(gridExtra)
library(grid)

source("../cluster_model_helper.R")

```


Loading model results.


```{r}

all_results <- readRDS("enet_multinomial_data/elastic_net_multinomial_results_k_4.RDS")
all_bounds <- readRDS("enet_multinomial_data/all_bounds.RDS")
bound_mult <- all_bounds$bound_mult

```



Getting cluster signatures.



```{r eval=FALSE, include=FALSE}
get_signature <- function(chosen_alpha, chosen_type){
  if (chosen_type == "Global"){
    data_mat <- global_mat_train
  } else if (chosen_type == "Phospho"){
    data_mat <- phospho_mat_train
  } else if (chosen_type == "RNA"){
    data_mat <- RNA_mat_train
  } else if (chosen_type == "Phospho_imp") {
    data_mat <- phospho_mat_train_imp
  } else if (chosen_type == "Combined"){
    data_mat <- combined_mat_train
  } else if (chosen_type == "Combined_v2"){
    data_mat <- combined_v2_mat_train
  }

  xx <- all_results[[chosen_type]]
  
  min_bounds <- all_bounds[[paste0("min_bounds_", chosen_type)]]
  max_bounds <- all_bounds[[paste0("max_bounds_", chosen_type)]]
  min_lambda <- min_bounds[as.character(chosen_alpha), ] %>% as.numeric()
  max_lambda <- max_bounds[as.character(chosen_alpha), ] %>% as.numeric()
  allowed_lambda <- (as.numeric(rownames(xx)) < max_lambda) & 
                    (as.numeric(rownames(xx)) > min_lambda)
  
  xx <- xx[allowed_lambda, ]
  col_name <- paste("alpha =", chosen_alpha)
  chosen_lambda <- rownames(xx)[[which.min(xx[[col_name]])]] %>%
    as.numeric()
  
  cluster_lab <- enet_meta %>%
    mutate(cluster_lab = paste("Cluster", k.4)) %>%
    pull(cluster_lab) %>%
    as.factor()
  names(cluster_lab) <- enet_meta$Barcode.ID
  cluster_lab <- cluster_lab[colnames(data_mat)]
  
  model <- glmnet(x = t(data_mat),
                  y = cluster_lab,
                  family = 'multinomial',
                  alpha = chosen_alpha,
                  lambda = chosen_lambda,
                  type.multinomial = "ungrouped")
  
  coefs <- coef(model, s = chosen_lambda)
  names(coefs) <- as.character(1:4)
  coefs <- lapply(names(coefs), function(xx_name){
    xx <- coefs[[xx_name]]
    data.frame(Cluster = xx_name, Gene = rownames(xx)[which(xx != 0)]) %>%
      filter(Gene != "(Intercept)")
  }) %>% do.call("rbind", .)
  
  signatures <- coefs %>%
    mutate(alpha = chosen_alpha, chosen_type = chosen_type, lambda = chosen_lambda)
  return(signatures)
}

signatures <- lapply(c("Global", "Phospho", "RNA", "Phospho_imp", "Combined", "Combined_v2"), function(chosen_type){
  lapply(c(0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0), function(chosen_alpha){
    test <- get_signature(chosen_alpha, chosen_type)
  }) %>% do.call("rbind", .)
}) %>% do.call("rbind", .)

write.table(signatures, "enet_multinomial_data/enet_multinomial_all_signatures.txt", 
            sep = "\t", quote = F)

```


```{r}
signatures <- read.table("enet_multinomial_data/enet_multinomial_all_signatures.txt", sep = "\t")

```


```{r eval=FALSE, include=FALSE}
signatures_synapse <- signatures %>%
  select(Cluster, Gene, alpha, chosen_type) %>%
  dplyr::rename(data_type = chosen_type) %>%
  filter(alpha == 0.7) %>%
  filter(data_type %in% c("Global", "Phospho", "RNA"))

signatures_synapse_combined <- signatures %>%
  select(Cluster, Gene, alpha, chosen_type) %>%
  dplyr::rename(data_type = chosen_type) %>%
  filter(alpha == 0.9) %>%
  filter(data_type %in% c("Combined", "Combined_v2")) %>%
  mutate(data_type = case_when(data_type == "Combined" ~ "Global + Phospho_imp",
                               data_type == "Combined_v2" ~ "Global + Phospho",
                               TRUE ~ data_type)) %>%
  rbind(signatures_synapse)

signatures_synapse_final <- signatures_synapse_combined %>%
  filter(data_type != "Global + Phospho_imp")

write.table(signatures_synapse_final, "enet_multinomial_data/enet_multinomial_signatures_k4.txt", sep = "\t")
upload.plot("enet_multinomial_data/enet_multinomial_signatures_k4.txt", "syn29612385")

```


Signature heatmap


```{r}
chosen.colors <- subtype_colors

signature_heatmap <- function(chosen_alpha, data_type, save_plot = TRUE){
  data_type_title <- data_type
  if (data_type == "Global"){
    data_mat <- global_mat_train
  } else if (data_type == "Phospho"){
    data_mat <- phospho_mat_train
  } else if (data_type == "RNA"){
    data_mat <- RNA_mat_train
  } else if (data_type == "Phospho_imp") {
    data_mat <- phospho_mat_train_imp
    data_type_title <- "Phospho imputed"
  } else if (data_type == "Combined"){
    data_mat <- combined_mat_train
    data_type_title <- "Global + Phospho imputed"
  } else if (data_type == "Combined_v2"){
    data_mat <- combined_v2_mat_train
    data_type_title <- "Global + Phospho"
  }
  
  signatures <- signatures %>%
    group_by(chosen_type, alpha, Gene) %>%
    dplyr::mutate(total = n()) %>%
    ungroup()
  
  row_df <- signatures %>%
    dplyr::filter(alpha == chosen_alpha) %>%
    dplyr::filter(chosen_type == data_type) %>%
    dplyr::select(Gene, Cluster) %>%
    group_by(Gene) %>%
    dplyr::mutate(total = n()) %>%
    dplyr::mutate(Cluster = case_when(total == 1 ~ as.character(Cluster),
                                      TRUE ~ "Mixed"),
                  Cluster = factor(Cluster, levels = c("1", "2", "3", "4", "Mixed"))) %>%
    unique() %>%
    as.data.frame()
  rownames(row_df) <- row_df$Gene
  
  col_df <- meta %>%
    dplyr::select(Barcode.ID) %>%
    merge(cluster_assignments, by = "Barcode.ID") %>%
    dplyr::select(k.4, Barcode.ID) %>%
    dplyr::rename(Cluster = k.4) %>%
    dplyr::mutate(Cluster = as.factor(Cluster)) 
  rownames(col_df) <- col_df$Barcode.ID
  col_df <- col_df %>%
    select(Cluster)
  
  ann_colors <- list("Cluster" = c("1" = chosen.colors[[1]], 
                                   "2" = chosen.colors[[2]],
                                   "3" = chosen.colors[[3]],
                                   "4" = chosen.colors[[4]],
                                   "Mixed" = "grey"))
  
  heatmap_breaks <- seq(-3, 3, by = 0.2)
  heatmap_colors <- colorRampPalette(rev(brewer.pal(n = 10, name = "RdBu")))(length(heatmap_breaks))
  cluster_row = pheatmap:::cluster_mat(data_mat[rownames(row_df), ], distance = "euclidean", 
                                       method = "ward.D")
  row_df <- row_df[cluster_row$order, ] %>%
    mutate(order = 1:n()) %>%
    arrange(Cluster) %>%
    select(Cluster)
  sigs <- rownames(row_df)
  file_path <- paste0("./enet_multinomial_data/signature_heatmap_", 
                      data_type, "_alpha_", chosen_alpha)
  
  if (save_plot){
    make.pheatmap(data_mat[sigs, ], filename = file_path, format = "png",
                  scale = "none", cluster_rows = FALSE, clustering_method = "ward.D", 
                  annotation_col = col_df, annotation_row = row_df, annotation_colors = ann_colors,
                  breaks = heatmap_breaks, color = heatmap_colors, show_rownames = F, show_colnames = F,
                  main = paste0(length(sigs), " total features, alpha = ", chosen_alpha, " ", data_type_title), 
                  height = 7, width = 7)
  }
    
  return(pheatmap(data_mat[sigs, ], scale = "none", cluster_rows = FALSE, clustering_method = "ward.D", 
                annotation_col = col_df, annotation_row = row_df, annotation_colors = ann_colors,
                breaks = heatmap_breaks, color = heatmap_colors, show_rownames = F, show_colnames = F,
                main = paste0(length(sigs), " total features, alpha = ", chosen_alpha, " ", data_type_title)))
}

signature_heatmap_v2 <- function(chosen_alpha){
  p_global <- signature_heatmap(chosen_alpha, "Global", save_plot = FALSE)
  p_phospho <- signature_heatmap(chosen_alpha, "Phospho", save_plot = FALSE)
  p_RNA <- signature_heatmap(chosen_alpha, "RNA", save_plot = FALSE)
  p_phospho_imp <- signature_heatmap(chosen_alpha, "Phospho_imp", save_plot = FALSE)
  p_combined <- signature_heatmap(chosen_alpha, "Combined", save_plot = FALSE)
  p_combined_v2 <- signature_heatmap(chosen_alpha, "Combined_v2", save_plot = FALSE)
  
  top_grob <- textGrob(paste0("Signatures alpha = ", chosen_alpha), 
                       gp = gpar(fontsize = 20))
  p_all <- arrangeGrob(p_global[[4]], p_RNA[[4]], p_phospho[[4]],
                       p_phospho_imp[[4]], p_combined[[4]], p_combined_v2[[4]],
                       ncol = 3, nrow = 2, top = top_grob)
  ggsave(paste0("enet_multinomial_data/signature_heatmaps_alpha_", chosen_alpha, ".pdf"), p_all, 
         width = 30, height = 25)
}

```



```{r}
lapply(c(0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0), function(chosen_alpha){
  signature_heatmap_v2(chosen_alpha)
})

signature_heatmap(0.7, "Global")
signature_heatmap(0.7, "RNA")
signature_heatmap(0.7, "Phospho")
signature_heatmap(0.9, "Global")
signature_heatmap(0.9, "Phospho")
signature_heatmap(0.9, "RNA")
signature_heatmap(0.9, "Combined_v2")

```



```{r}
sigs_global <- signatures %>%
  filter(chosen_type == "Global",
         alpha == 0.7) %>% 
  select(Gene, chosen_type) %>%
  unique()

sigs_global_phospho <- signatures %>%
  filter(chosen_type == "Combined_v2",
         alpha == 0.9) %>% 
  select(Gene, chosen_type) %>%
  unique() %>%
  mutate(type = case_when(grepl("-", Gene) ~ "Phospho",
                          TRUE ~ "Global"))

sigs_global_phospho_imputed <- signatures %>%
  filter(chosen_type == "Combined",
         alpha == 0.9) %>% 
  select(Gene, chosen_type) %>%
  unique() %>%
  mutate(type = case_when(grepl("-", Gene) ~ "Phospho",
                          TRUE ~ "Global"))


```


