---
title: "PTRC Ex10 Batch correction and normalization"
author: "Michael Nestor"
date: "`r format(Sys.Date(), '%m/%d/%Y')`"
output: html_document
---

```{r setup}
library(MSnSet.utils)
library(NMF)
library(dplyr)
library(tibble)
library(tidyr)
library(ggplot2)


source("../../util/synapseUtil.R")
source("../../util/loading_data.R")
source("NMF helper.R")
load("../../Misc/loaded data.RData")

# load.combined.data()
```


```{r}
mat.global <- global.data %>%
  pivot_wider(names_from = Barcode.ID, values_from = LogRatio) %>%
  column_to_rownames("Gene") %>%
  as.matrix()


mat.phospho <- phospho.data %>%
  select(SiteID, Barcode.ID, LogRatio) %>%
  pivot_wider(names_from = Barcode.ID, values_from = LogRatio) %>%
  column_to_rownames("SiteID") %>%
  as.matrix()

## Data is complete, no need to impute.
mat.RNA <- RNA.data %>%
  pivot_wider(names_from = Barcode.ID, values_from = `RNA counts`) %>%
  column_to_rownames("Gene") %>%
  as.matrix()


mat <- prepare.nmf.mat(list(mat.global, mat.phospho, mat.RNA))

```

Clearly k = 4 and k = 2 give the best, most stable results.


```{r load raw results}
files <- list.files("Data/", "BEATAML NMF") %>%
  paste0("Data/", .)

results <- lapply(files, readRDS)

plots <- lapply(results, consensusmap)

```


```{r}
coph.correlation <- sapply(results, cophcor) %>%
  data.frame(coph.cor = ., k = 2:7)

p <- ggplot(coph.correlation, aes(x = k, y = coph.cor)) + geom_line()
p
```


PCA does not seem to capture these clusters very well. Using k = 4, which gave the highest cophenetic value.

```{r}
m.phospho <- make.msnset(phospho.data, feature.col = "SiteID", metadata = meta)
m.global <- make.msnset(global.data, feature.col = "Gene", metadata = meta)
m.RNA <- make.msnset(RNA.data, feature.col = "Gene", metadata = meta, value.col = "RNA counts")

clusters <- get.clusters(results[[3]])

m.phospho <- m.phospho[, clusters$Sample]
m.global <- m.global[, clusters$Sample]

pData(m.phospho)$Cluster <- clusters[sampleNames(m.phospho), "Cluster"] %>% as.factor()
pData(m.global)$Cluster <- clusters[sampleNames(m.global), "Cluster"] %>% as.factor()
pData(m.RNA)$Cluster <- clusters[sampleNames(m.RNA), "Cluster"] %>% as.factor()

```

```{r}
plot_pca_v4(m.phospho, "Cluster", show.ellipse = FALSE) + ggtitle("Phospho")
plot_pca_v4(m.global, "Cluster", show.ellipse = FALSE) + ggtitle("Global")
plot_pca_v4(m.RNA, "Cluster", show.ellipse = FALSE) + ggtitle("RNA")

```

```{r}
rownames(m.RNA) <- paste0(rownames(m.RNA), "extra")
mat.combined <- rbind(exprs(m.phospho), exprs(m.global), exprs(m.RNA))

means <- apply(mat.combined, 1, mean, na.rm = T)
mat.combined <- sweep(mat.combined, 1, means, FUN = '-')
sds <- apply(mat.combined, 1, sd, na.rm = T)
mat.combined <- sweep(mat.combined, 1, sds, FUN = "/")

m.combined <- MSnSet(exprs = mat.combined)
pData(m.combined) <- pData(m.phospho)

plot_pca_v4(m.combined, "Cluster", show.ellipse = FALSE)

```










