---
title: "PTRC Ex10 Creation of study design tables"
author: "Michael Nestor (michael.nestor@pnnl.gov)"
output: html_document
---

```{r}
library(PlexedPiper)
library(stringr)
library(dplyr)
library(PNNL.DMS.utils)

path_to_global_study_design <- "study_design/Ex10_global_study_design/"
path_to_phospho_study_design <- "study_design/Ex10_phospho_study_design/"
path_to_acetyl_study_design <- "study_design/Ex10_acetyl_study_design/"

global_data_package_num <- 3676
phospho_data_package_num <- 3723
acetyl_data_package_num <- 5378
```

```{r}
job_records <- get_job_records_by_dataset_package(global_data_package_num)

fractions <- job_records %>%
  select(Dataset) %>%
  distinct() %>%
  mutate(PlexID = str_extract(Dataset, "Plex_\\d\\d"))
head(fractions)

write.table(fractions, file=file.path(path_to_global_study_design, "fractions.txt"),
            quote=F, sep="\t", row.names=F)
```

```{r}
job_records <- get_job_records_by_dataset_package(phospho_data_package_num)

fractions <- job_records %>%
  select(Dataset) %>%
  distinct() %>%
  mutate(PlexID = str_extract(Dataset, "Plex_\\d\\d"))
head(fractions)

write.table(fractions, file=file.path(path_to_phospho_study_design, "fractions.txt"),
            quote=F, sep="\t", row.names=F)
```

```{r}
job_records <- get_job_records_by_dataset_package(acetyl_data_package_num)

fractions <- job_records %>%
  select(Dataset) %>%
  distinct() %>%
  mutate(PlexID = str_extract(Dataset, "Plex_\\d\\d"))
head(fractions)

write.table(fractions, file=paste0(path_to_acetyl_study_design, "fractions.txt"),
            quote=F, sep="\t", row.names=FALSE)
```

Samples and fractions table must be created from study-specific metadata. See `r help(read_study_design)` for more information.

```{r}
library(readxl)

samples <- read_xlsx("data/TMTmappingTable.xlsx") 
samples <- samples %>%
  select(ReporterAlias=`sampleID`,
         PlexID=Plex,
         ReporterName=Channel) %>%
  mutate(QuantBlock=1, MeasurementName = if_else(ReporterAlias=="Ref",
                                                 NA_character_,
                                                 ReporterAlias),
         PlexID = paste0("Plex_", sprintf("%02d", PlexID))) %>%
  select(PlexID, QuantBlock, ReporterName, ReporterAlias, MeasurementName)
head(samples)

references <- samples %>%
  filter(grepl("Reference", MeasurementName)) %>%
  select(PlexID, QuantBlock, Reference=ReporterAlias)
head(references)


write.table(samples, file=file.path(path_to_global_study_design, "samples.txt"),
            quote=F, sep="\t", row.names=F)
write.table(references, file=file.path(path_to_global_study_design, "references.txt"),
            quote=F, sep="\t", row.names=F)

write.table(samples, file=file.path(path_to_phospho_study_design, "samples.txt"),
            quote=F, sep="\t", row.names=F)
write.table(references, file=file.path(path_to_phospho_study_design, "references.txt"),
            quote=F, sep="\t", row.names=F)

write.table(samples, file=file.path(path_to_acetyl_study_design, "samples.txt"),
            quote=F, sep="\t", row.names=F)
write.table(references, file=file.path(path_to_acetyl_study_design, "references.txt"),
            quote=F, sep="\t", row.names=F)
```