---
title: "PTRC Ex10 Batch correction and normalization"
author: "Michael Nestor"
date: "`r format(Sys.Date(), '%m/%d/%Y')`"
output: html_document
---

```{r setup}
library(MSnSet.utils)
library(sva)
library(dplyr)
library(tibble)
library(tidyr)

library(devtools)
source("../dataProcessing/proteomicsNormalizationMethods.R")
source("../util/synapseUtil.R")
```

# Load metadata

```{r load_metadata}
## Selecting original global and phospho data
phenodata.syn <- "syn25807733"
phospho.syn <- "syn25714936"
global.syn <- "syn25714254"

syn <- synapseLogin()

phenodata <- read.table(syn$get(phenodata.syn)$path, sep = "\t",
                         header = TRUE, colClasses = "character") %>%
  column_to_rownames("SampleID.abbrev")
phenodata$Plex <- as.character(phenodata$Plex)
phenodata$Loading.Mass <- as.numeric(phenodata$Loading.Mass)

crosstab <- read.table(syn$get(phospho.syn)$path, check.names = F, sep = "\t")

global_crosstab <- read.table(syn$get(global.syn)$path, check.names = F, sep = "\t")

path_to_crosstab <- "data/Batch Correction/ptrc_ex10_crosstab_phospho_siteID_original_relaxed.txt"

# corrected.synapse <- read.table("data/Batch Correction/ptrc_ex10_crosstab_phospho_siteID_corrected.txt",
#                                 check.names = F, sep = "\t")

```


# Normalize and correct phospho data


```{r normalize_phospho_data}
## Performing the exact same normalization and correction steps, with the "sufficiently present" features
## filter considerably relaxed, allowing no more than 4 plexes to be missing per SiteID.
n.sigfig <- 3
n.plexes <- 10

m <- MSnSet(as.matrix(crosstab))
pData(m) <- phenodata[sampleNames(m),]

# Fetch global sample medians
global_coeffs <- apply(global_crosstab, MARGIN = 2, FUN = median, na.rm = T)

# Normalize by global sample medians
exprs(m) <- sweep(exprs(m), 2, global_coeffs)
m <- normalizeByMedpolish(m)
new_path_to_crosstab <- sub("_original", "_medpolish", path_to_crosstab)
write.table(signif(exprs(m), n.sigfig),
            file = new_path_to_crosstab,
            quote=F, sep="\t")

meta <- phenodata %>%
  select(Plex) %>%
  rownames_to_column("Sample")

m.medpolish <- m

## Filtering by missing batches, no more than 4 allowed
xx <- as.data.frame(exprs(m)) %>%
  mutate(SiteID = rownames(.)) %>%
  pivot_longer(-SiteID, names_to = "Sample", values_to = "LogRatio") %>%
  left_join(meta, by = "Sample") %>%
  group_by(SiteID, Plex) %>%
  mutate(count = sum(!is.na(LogRatio))) %>%
  ungroup(Plex, SiteID) %>%
  group_by(SiteID) %>%
  summarise(`Plexes missing` = sum(count == 0)/10)

chosen <- xx %>%
  filter(`Plexes missing` <= n.plexes) 

chosen <- chosen$SiteID
m <- m[chosen, ]

## Filering by no more than 50% missing per feature (different than above)
m <- filterByProportionMissingValues(m, least_proportion_threshold = 0.5)
    
# Batch correction
removed_covariates <- c("Plex", "Loading.Mass")

########################### NOTE #############################
# m <- correct_batch_effect_empiricalBayesLM(m, removed_covariates)
## The regression (used to estimate batch and loading mass effect) fails for 4125
## Phosphosites. Reason has to do with the design matrix in regression not having full rank.
## To see what the sites are, debug WGCNA::empiricalBayesLM and proceed past line 250. This ensures 
## the regression has run for all sites. Then we can save the sites which failed to a new table using
## write.table(colnames(data)[which(regressionValid == FALSE)], "Failed Regression.txt", row.names = F)
#######################################################
# debug(WGCNA::empiricalBayesLM)
failed.sites <- read.table("../proteomics/data/Batch Correction/Failed Regression.txt")[-1, ]
m <- m[!(rownames(m) %in% failed.sites), ]
m <- correct_batch_effect_empiricalBayesLM(m, removed_covariates)

# Medpolish and save
m <- normalizeByMedpolish(m)
new_path_to_crosstab <- sub("_original", "_corrected", path_to_crosstab)
write.table(signif(exprs(m), n.sigfig),
            file = new_path_to_crosstab,
            quote=F, sep="\t")

```

```{r push to synapse}
meta <- phenodata %>%
  rownames_to_column("Sample")

data <- exprs(m) %>%
  signif(n.sigfig) %>%
  as.data.frame() %>%
  rownames_to_column("SiteID") %>%
  mutate(Gene = sub("(^.+)-.+", "\\1", SiteID)) %>%
  select(Gene, SiteID, everything()) %>%
  pivot_longer(cols = c(-SiteID, -Gene), names_to = "Sample", values_to = "LogRatio") %>%
  filter(!is.na(LogRatio)) %>%
  left_join(meta, by = "Sample")

synTableStore(data, "BeatAML Phosphoproteomics relaxed_filter_v2_corrected", parentId = 'syn22128879')

```


